<a href="https://colab.research.google.com/github/christophehenrynda/py-bot-learn/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import torch

LISTS

In [5]:
my_lists = [[1,2,3,4,5],[1,"a",2]]
my_lists


[[1, 2, 3, 4, 5], [1, 'a', 2]]

NUMPY LISTS

In [9]:
np1 = np.random.rand(2, 2)
np1

array([[0.35559919, 0.0334303 ],
       [0.14677581, 0.70467285]])

In [10]:
np1.dtype


dtype('float64')

TENSOR



In [14]:
tens_2d = torch.rand(2,2)
tens_2d

tensor([[0.2229, 0.5990],
        [0.9234, 0.1953]])

In [15]:
tens_np = torch.tensor(np1)
tens_np

tensor([[0.3556, 0.0334],
        [0.1468, 0.7047]], dtype=torch.float64)